//------------------------------------------------------------------------------
export function getPid(pidId, modeId = 1) {
  const service = pids[modeId];
  return service && service[pidId];
}

export default () => pids;

//------------------------------------------------------------------------------
const pids = {
  0x01: {
    0x00: {
      bytes: 4,
      name: 'pidsupp0',
      description: 'PIDs supported 00-20',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x01: {
      bytes: 4,
      name: 'dtc_cnt',
      description: 'Monitor status since DTCs cleared',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x02: {
      bytes: 2,
      name: 'dtcfrzf',
      description: 'DTC that caused required freeze frame data storage',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x03: {
      bytes: 2,
      name: 'fuelsys',
      description: 'Fuel system 1 and 2 status',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x04: {
      bytes: 1,
      name: 'load_pct',
      description: 'Calculated LOAD Value',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x05: {
      bytes: 1,
      name: 'temp',
      description: 'Engine Coolant Temperature',
      min: -40,
      max: 215,
      unit: '°C',
    },
    0x06: {
      bytes: 1,
      name: 'shrtft13',
      description: 'Short Term Fuel Trim - Bank 1,3',
      min: -100,
      max: 99.22,
      unit: '%',
    },
    0x07: {
      bytes: 1,
      name: 'longft13',
      description: 'Long Term Fuel Trim - Bank 1,3',
      min: -100,
      max: 99.22,
      unit: '%',
    },
    0x08: {
      bytes: 1,
      name: 'shrtft24',
      description: 'Short Term Fuel Trim - Bank 2,4',
      min: -100,
      max: 99.22,
      unit: '%',
    },
    0x09: {
      bytes: 1,
      name: 'longft24',
      description: 'Long Term Fuel Trim - Bank 2,4',
      min: -100,
      max: 99.22,
      unit: '%',
    },
    0x0a: {
      bytes: 1,
      name: 'frp',
      description: 'Fuel Pressure',
      min: 0,
      max: 765,
      unit: 'kPa',
    },
    0x0b: {
      bytes: 1,
      name: 'map',
      description: 'Intake Manifold Absolute Pressure',
      min: 0,
      max: 255,
      unit: 'kPa',
    },
    0x0c: {
      bytes: 2,
      name: 'rpm',
      description: 'Engine RPM',
      min: 0,
      max: 16383.75,
      unit: 'rev/min',
    },
    0x0d: {
      bytes: 1,
      name: 'vss',
      description: 'Vehicle Speed Sensor',
      min: 0,
      max: 255,
      unit: 'km/h',
    },
    0x0e: {
      bytes: 1,
      name: 'sparkadv',
      description: 'Ignition Timing Advance for #1 Cylinder',
      min: -64,
      max: 63.5,
      unit: 'degrees relative to #1 cylinder',
    },
    0x0f: {
      bytes: 1,
      name: 'iat',
      description: 'Intake Air Temperature',
      min: -40,
      max: 215,
      unit: '°C',
    },
    0x10: {
      bytes: 2,
      name: 'maf',
      description: 'Air Flow Rate from Mass Air Flow Sensor',
      min: 0,
      max: 655.35,
      unit: 'g/s',
    },
    0x11: {
      bytes: 1,
      name: 'throttlepos',
      description: 'Absolute Throttle Position',
      min: 1,
      max: 100,
      unit: '%',
    },
    0x12: {
      bytes: 1,
      name: 'air_stat',
      description: 'Commanded Secondary Air Status',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x13: {
      bytes: 1,
      name: 'o2sloc',
      description: 'Location of Oxygen Sensors',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x14: {
      bytes: 2,
      name: ['Oxygen Sensor 1 Voltage', 'Oxygen Sensor 1 Short term fuel trim'],
      description: 'Bank 1 - Sensor 1/Bank 1 - Sensor 1 Oxygen Sensor Output Voltage / Short Term Fuel Trim',
      min: 0,
      max: 1.275,
      unit: ['V', '%'],
    },
    0x15: {
      bytes: 2,
      name: ['Oxygen Sensor 2 Voltage', 'Oxygen Sensor 2 Short term fuel trim'],
      description: 'Bank 1 - Sensor 2/Bank 1 - Sensor 2 Oxygen Sensor Output Voltage / Short Term Fuel Trim',
      min: 0,
      max: 1.275,
      unit: ['V', '%'],
    },
    0x16: {
      bytes: 2,
      name: ['Oxygen Sensor 3 Voltage', 'Oxygen Sensor 3 Short term fuel trim'],
      description: 'Bank 1 - Sensor 3/Bank 2 - Sensor 1 Oxygen Sensor Output Voltage / Short Term Fuel Trim',
      min: 0,
      max: 1.275,
      unit: ['V', '%'],
    },
    0x17: {
      bytes: 2,
      name: ['Oxygen Sensor 4 Voltage', 'Oxygen Sensor 4 Short term fuel trim'],
      description: 'Bank 1 - Sensor 4/Bank 2 - Sensor 2 Oxygen Sensor Output Voltage / Short Term Fuel Trim',
      min: 0,
      max: 1.275,
      unit: ['V', '%'],
    },
    0x18: {
      bytes: 2,
      name: ['Oxygen Sensor 5 Voltage', 'Oxygen Sensor 5 Short term fuel trim'],
      description: 'Bank 2 - Sensor 1/Bank 3 - Sensor 1 Oxygen Sensor Output Voltage / Short Term Fuel Trim',
      min: 0,
      max: 1.275,
      unit: ['V', '%'],
    },
    0x19: {
      bytes: 2,
      name: ['Oxygen Sensor 6 Voltage', 'Oxygen Sensor 6 Short term fuel trim'],
      description: 'Bank 2 - Sensor 2/Bank 3 - Sensor 2 Oxygen Sensor Output Voltage / Short Term Fuel Trim',
      min: 0,
      max: 1.275,
      unit: ['V', '%'],
    },
    0x1a: {
      bytes: 2,
      name: ['Oxygen Sensor 7 Voltage', 'Oxygen Sensor 7 Short term fuel trim'],
      description: 'Bank 2 - Sensor 3/Bank 4 - Sensor 1 Oxygen Sensor Output Voltage / Short Term Fuel Trim',
      min: 0,
      max: 1.275,
      unit: ['V', '%'],
    },
    0x1b: {
      bytes: 2,
      name: ['Oxygen Sensor 8 Voltage', 'Oxygen Sensor 8 Short term fuel trim'],
      description: 'Bank 2 - Sensor 4/Bank 4 - Sensor 2 Oxygen Sensor Output Voltage / Short Term Fuel Trim',
      min: 0,
      max: 1.275,
      unit: ['V', '%'],
    },
    0x1c: {
      bytes: 1,
      name: 'obdsup',
      description: 'OBD requirements to which vehicle is designed',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x1d: {
      bytes: 1,
      name: 'o2sloc2',
      description: 'Location of oxygen sensors',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x1e: {
      bytes: 1,
      name: 'pto_stat',
      description: 'Auxiliary Input Status',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x1f: {
      bytes: 2,
      name: 'runtm',
      description: 'Time Since Engine Start',
      min: 0,
      max: 65535,
      unit: 'seconds',
    },
    0x20: {
      bytes: 4,
      name: 'piddsupp2',
      description: 'PIDs supported 21-40',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x21: {
      bytes: 2,
      name: 'mil_dist',
      description: 'Distance Travelled While MIL is Activated',
      min: 0,
      max: 65535,
      unit: 'km',
    },
    0x22: {
      bytes: 2,
      name: 'frpm',
      description: 'Fuel Rail Pressure relative to manifold vacuum',
      min: 0,
      max: 5177.265,
      unit: 'kPa',
    },
    0x23: {
      bytes: 2,
      name: 'frpd',
      description: 'Fuel Rail Pressure (diesel)',
      min: 0,
      max: 655350,
      unit: 'kPa',
    },
    0x24: {
      bytes: 4,
      name: ['Oxygen Sensor 1 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 1 Voltage'],
      description: 'Bank 1 - Sensor 1/Bank 1 - Sensor 1 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Voltage',
      min: 0,
      max: 2,
      unit: ['ratio', 'V'],
    },
    0x25: {
      bytes: 4,
      name: ['Oxygen Sensor 2 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 2 Voltage'],
      description: 'Bank 1 - Sensor 2/Bank 1 - Sensor 2 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Voltage',
      min: 0,
      max: 2,
      unit: ['ratio', 'V'],
    },
    0x26: {
      bytes: 4,
      name: ['Oxygen Sensor 3 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 3 Voltage'],
      description: 'Bank 1 - Sensor 3 /Bank 2 - Sensor 1(wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Voltage',
      min: 0,
      max: 2,
      unit: ['ratio', 'V'],
    },
    0x27: {
      bytes: 4,
      name: ['Oxygen Sensor 4 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 4 Voltage'],
      description: 'Bank 1 - Sensor 4 /Bank 2 - Sensor 2(wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Voltage',
      min: 0,
      max: 2,
      unit: ['ratio', 'V'],
    },
    0x28: {
      bytes: 4,
      name: ['Oxygen Sensor 5 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 5 Voltage'],
      description: 'Bank 2 - Sensor 1 /Bank 3 - Sensor 1(wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Voltage',
      min: 0,
      max: 2,
      unit: ['ratio', 'V'],
    },
    0x29: {
      bytes: 4,
      name: ['Oxygen Sensor 6 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 6 Voltage'],
      description: 'Bank 2 - Sensor 2 /Bank 3 - Sensor 2(wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Voltage',
      min: 0,
      max: 2,
      unit: ['ratio', 'V'],
    },
    0x2a: {
      bytes: 4,
      name: ['Oxygen Sensor 7 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 7 Voltage'],
      description: 'Bank 2 - Sensor 3 /Bank 4 - Sensor 1(wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Voltage',
      min: 0,
      max: 2,
      unit: ['ratio', 'V'],
    },
    0x2b: {
      bytes: 4,
      name: ['Oxygen Sensor 8 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 8 Voltage'],
      description: 'Bank 2 - Sensor 4 /Bank 4 - Sensor 2(wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Voltage',
      min: 0,
      max: 2,
      unit: ['ratio', 'V'],
    },
    0x2c: {
      bytes: 1,
      name: 'egr_pct',
      description: 'Commanded EGR',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x2d: {
      bytes: 1,
      name: 'egr_err',
      description: 'EGR Error',
      min: -100,
      max: 99.22,
      unit: '%',
    },
    0x2e: {
      bytes: 1,
      name: 'evap_pct',
      description: 'Commanded Evaporative Purge',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x2f: {
      bytes: 1,
      name: 'fli',
      description: 'Fuel Level Input',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x30: {
      bytes: 1,
      name: 'warm_ups',
      description: 'Number of warm-ups since diagnostic trouble codes cleared',
      min: 0,
      max: 255,
      unit: '',
    },
    0x31: {
      bytes: 2,
      name: 'clr_dist',
      description: 'Distance since diagnostic trouble codes cleared',
      min: 0,
      max: 65535,
      unit: 'km',
    },
    0x32: {
      bytes: 2,
      name: 'evap_vp',
      description: 'Evap System Vapour Pressure',
      min: -8192,
      max: 8192,
      unit: 'Pa',
    },
    0x33: {
      bytes: 1,
      name: 'baro',
      description: 'Barometric Pressure',
      min: 0,
      max: 255,
      unit: 'kPa',
    },
    0x34: {
      bytes: 4,
      name: ['Oxygen Sensor 1 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 1 Current'],
      description: 'Bank 1 - Sensor 1/Bank 1 - Sensor 1 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Current',
      min: 0,
      max: 2,
      unit: ['ratio', 'mA'],
    },
    0x35: {
      bytes: 4,
      name: ['Oxygen Sensor 2 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 2 Current'],
      description: 'Bank 1 - Sensor 2/Bank 1 - Sensor 2 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Current',
      min: 0,
      max: 2,
      unit: ['ratio', 'mA'],
    },
    0x36: {
      bytes: 4,
      name: ['Oxygen Sensor 3 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 3 Current'],
      description: 'Bank 1 - Sensor 3/Bank 2 - Sensor 1 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Current',
      min: 0,
      max: 2,
      unit: ['ratio', 'mA'],
    },
    0x37: {
      bytes: 4,
      name: ['Oxygen Sensor 4 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 4 Current'],
      description: 'Bank 1 - Sensor 4/Bank 2 - Sensor 2 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Current',
      min: 0,
      max: 2,
      unit: ['ratio', 'mA'],
    },
    0x38: {
      bytes: 4,
      name: ['Oxygen Sensor 5 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 5 Current'],
      description: 'Bank 2 - Sensor 1/Bank 3 - Sensor 1 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Current',
      min: 0,
      max: 2,
      unit: ['ratio', 'mA'],
    },
    0x39: {
      bytes: 4,
      name: ['Oxygen Sensor 6 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 6 Current'],
      description: 'Bank 2 - Sensor 2/Bank 3 - Sensor 2 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Current',
      min: 0,
      max: 2,
      unit: ['ratio', 'mA'],
    },
    0x3a: {
      bytes: 4,
      name: ['Oxygen Sensor 7 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 7 Current'],
      description: 'Bank 2 - Sensor 3/Bank 4 - Sensor 1 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Current',
      min: 0,
      max: 2,
      unit: ['ratio', 'mA'],
    },
    0x3b: {
      bytes: 4,
      name: ['Oxygen Sensor 8 Air-Fuel Equivalence Ratio (λ)', 'Oxygen Sensor 8 Current'],
      description: 'Bank 2 - Sensor 4/Bank 4 - Sensor 2 (wide range O2S) Oxygen Sensors Equivalence Ratio (lambda) / Current',
      min: 0,
      max: 2,
      unit: ['ratio', 'mA'],
    },
    0x3c: {
      bytes: 2,
      name: 'catemp11',
      description: 'Catalyst Temperature Bank 1 /  Sensor 1',
      min: -40,
      max: 6513.5,
      unit: '°C',
    },
    0x3d: {
      bytes: 2,
      name: 'catemp21',
      description: 'Catalyst Temperature Bank 2 /  Sensor 1',
      min: -40,
      max: 6513.5,
      unit: '°C',
    },
    0x3e: {
      bytes: 2,
      name: 'catemp12',
      description: 'Catalyst Temperature Bank 1 /  Sensor 2',
      min: -40,
      max: 6513.5,
      unit: '°C',
    },
    0x3f: {
      bytes: 2,
      name: 'catemp22',
      description: 'Catalyst Temperature Bank 2 /  Sensor 2',
      min: -40,
      max: 6513.5,
      unit: '°C',
    },
    0x40: {
      bytes: 4,
      name: 'piddsupp4',
      description: 'PIDs supported 41-60',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x41: {
      bytes: 4,
      name: 'monitorstat',
      description: 'Monitor status this driving cycle',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x42: {
      bytes: 2,
      name: 'vpwr',
      description: 'Control module voltage',
      min: 0,
      max: 65535,
      unit: 'V',
    },
    0x43: {
      bytes: 2,
      name: 'load_abs',
      description: 'Absolute Load Value',
      min: 0,
      max: 25700,
      unit: '%',
    },
    0x44: {
      bytes: 2,
      name: 'lambda',
      description: 'Fuel/air Commanded Equivalence Ratio',
      min: 0,
      max: 2,
      unit: '(ratio)',
    },
    0x45: {
      bytes: 1,
      name: 'tp_r',
      description: 'Relative Throttle Position',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x46: {
      bytes: 1,
      name: 'aat',
      description: 'Ambient air temperature',
      min: -40,
      max: 215,
      unit: '°C',
    },
    0x47: {
      bytes: 1,
      name: 'tp_b',
      description: 'Absolute Throttle Position B',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x48: {
      bytes: 1,
      name: 'tp_c',
      description: 'Absolute Throttle Position C',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x49: {
      bytes: 1,
      name: 'app_d',
      description: 'Accelerator Pedal Position D',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x4a: {
      bytes: 1,
      name: 'app_e',
      description: 'Accelerator Pedal Position E',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x4b: {
      bytes: 1,
      name: 'app_f',
      description: 'Accelerator Pedal Position F',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x4c: {
      bytes: 1,
      name: 'tac_pct',
      description: 'Commanded Throttle Actuator Control',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x4d: {
      bytes: 2,
      name: 'mil_time',
      description: 'Time run by the engine while MIL activated',
      min: 0,
      max: 65535,
      unit: 'minutes',
    },
    0x4e: {
      bytes: 2,
      name: 'clr_time',
      description: 'Time since diagnostic trouble codes cleared',
      min: 0,
      max: 65535,
      unit: 'minutes',
    },
    0x4f: {
      bytes: 4,
      name: [
        'Maximum value for Fuel–Air equivalence ratio',
        'Maximum value oxygen sensor voltage',
        'Maximum value oxygen sensor current',
        'Maximum value intake manifold absolute pressure',
      ],
      description: 'External Test Equipment Configuration #1',
      min: 0,
      max: 0,
      unit: ['ratio', 'V', 'mA', 'kPa'],
    },
    0x50: {
      bytes: 4,
      name: 'exttest2',
      description: 'External Test Equipment Configuration #2',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x51: {
      bytes: 1,
      name: 'fuel_type',
      description: 'Fuel Type',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x52: {
      bytes: 1,
      name: 'alch_pct',
      description: 'Ethanol fuel %',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x53: {
      bytes: 2,
      name: 'abs_vp',
      description: 'Absolute Evap system Vapor Pressure',
      min: 0,
      max: 327675,
      unit: 'kPa',
    },
    0x54: {
      bytes: 2,
      name: 'system_vp',
      description: 'Evap system vapor pressure',
      min: -32767,
      max: 32767,
      unit: 'Pa',
    },
    0x55: {
      bytes: 2,
      name: ['Short term secondary oxygen sensor trim bank 1', 'Short term secondary oxygen sensor trim bank 3'],
      description: 'Short term secondary oxygen sensor trim bank 1 and bank 3',
      min: -100,
      max: 99.22,
      unit: ['%', '%'],
    },
    0x56: {
      bytes: 2,
      name: ['Long term secondary oxygen sensor trim bank 1', 'Long term secondary oxygen sensor trim bank 3'],
      description: 'Long term secondary oxygen sensor trim bank 1 and bank 3',
      min: -100,
      max: 99.22,
      unit: ['%', '%'],
    },
    0x57: {
      bytes: 2,
      name: ['Short term secondary oxygen sensor trim bank 2', 'Short term secondary oxygen sensor trim bank 4'],
      description: 'Short term secondary oxygen sensor trim bank 2 and bank 4',
      min: -100,
      max: 99.22,
      unit: ['%', '%'],
    },
    0x58: {
      bytes: 2,
      name: ['Long term secondary oxygen sensor trim bank 2', 'Long term secondary oxygen sensor trim bank 4'],
      description: 'Long term secondary oxygen sensor trim bank 2 and bank 4',
      min: -100,
      max: 99.22,
      unit: ['%', '%'],
    },
    0x59: {
      bytes: 2,
      name: 'frp_abs',
      description: 'Fuel rail pressure (absolute)',
      min: 0,
      max: 655350,
      unit: 'kPa',
    },
    0x5a: {
      bytes: 1,
      name: 'pedalpos',
      description: 'Relative accelerator pedal position',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x5b: {
      bytes: 1,
      name: 'hybridlife',
      description: 'Hybrid battery pack remaining life',
      min: 0,
      max: 100,
      unit: '%',
    },
    0x5c: {
      bytes: 1,
      name: 'engineoilt',
      description: 'Engine oil temperature',
      min: -40,
      max: 210,
      unit: '°C',
    },
    0x5d: {
      bytes: 2,
      name: 'finjtiming',
      description: 'Fuel injection timing',
      min: -210,
      max: 301.992,
      unit: '°',
    },
    0x5e: {
      bytes: 2,
      name: 'enginefrate',
      description: 'Engine fuel rate',
      min: 0,
      max: 3212.75,
      unit: 'L/h',
    },
    0x5f: {
      bytes: 1,
      name: 'emmissionreq',
      description: 'Emission requirements to which vehicle is designed',
      min: 0,
      max: 0,
      unit: 'Bit Encoded',
    },
    0x60: {
      bytes: 4,
      name: 'pid_96',
      description: 'PIDs supported [0x61 - 0x80]',
      min: 0,
      max: 0,
      unit: '',
    },
    0x61: {
      bytes: 1,
      name: 'pid_97',
      description: "Driver's demand engine - percent torque",
      min: 0,
      max: 0,
      unit: '%',
    },
    0x62: {
      bytes: 1,
      name: 'aet',
      description: 'Actual engine - percent torque',
      min: -125,
      max: 125,
      unit: '%',
    },
    0x63: {
      bytes: 2,
      name: 'pid_99',
      description: 'Engine reference torque',
      min: 0,
      max: 0,
      unit: 'Nm',
    },
    0x64: {
      bytes: 5,
      name: 'pid_100',
      description: 'Engine percent torque data',
      min: 0,
      max: 0,
      unit: '%',
    },
    0x65: {
      bytes: 2,
      name: 'pid_101',
      description: 'Auxiliary input / output supported',
      min: 0,
      max: 0,
      unit: '',
    },
    0x66: {
      bytes: 5,
      name: 'pid_102',
      description: 'Mass air flow sensor',
      min: 0,
      max: 0,
      unit: 'grams/sec',
    },
    0x67: {
      bytes: 3,
      name: 'ect',
      description: 'Engine coolant temperature',
      min: -40,
      max: 215,
      unit: '°C',
    },
    0x68: {
      bytes: 3,
      name: 'pid_104',
      description: 'Intake air temperature sensor',
      min: 0,
      max: 0,
      unit: '°C',
    },
    0x69: {
      bytes: 5,
      name: 'egrt',
      description: 'Exhaust gas recirculation temperature',
      min: -40,
      max: 215,
      unit: '°C',
    },
    0x6a: {
      bytes: 6,
      name: 'fpc',
      description: 'Fuel pressure control system',
      min: -40,
      max: 215,
      unit: '°C',
    },
    0x6b: {
      bytes: 5,
      name: 'ipct',
      description: 'Injection pressure control system',
      min: -40,
      max: 215,
      unit: '°C',
    },
    0x6c: {
      bytes: 5,
      name: 'ep',
      description: 'Exhaust pressure',
      min: -40,
      max: 215,
      unit: '',
    },
    0x6d: {
      bytes: 9,
      name: 'egt',
      description: 'Exhaust Gas temperature Bank 1',
      min: -40,
      max: 215,
      unit: '°C',
    },
    0xa6: {
      bytes: 4,
      name: 'pid_166',
      description: 'Odometer',
      min: 0,
      max: 0,
      unit: 'km',
    },
  },
};
